export const GET_CONTACTS = "GET_CONTACTS"
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL"
export const ADD_CONTACT = "ADD_CONTACT"
export const ADD_CONTACT_FAIL ="ADD_CONTACT_FAIL"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const UPDATE_CONTACT = "UPDATE_CONTACT"
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL"
export const GET_BY_ID = "GET_BY_ID"
export const CLEAR_CONTACT_BY_ID = "CLEAR_CONTACT_BY_ID"



